import { CommandType } from './CommandType';
import {
  NoteSequence,
  StartCommand,
  EndCommand,
  MeasureCommand,
  BPMChangeCommand,
  DelayCommand,
  ScrollCommand,
  GoGoStartCommand,
  GoGoEndCommand,
  BarLineOffCommand,
  BarLineOnCommand,
  BranchStartCommand,
  BranchEndCommand,
  SectionCommand,
  LyricCommand,
  LevelHoldCommand,
  BMScrollCommand,
  HBScrollCommand,
  NextSongCommand,
  DirectionCommand,
  SuddenCommand,
  BranchMarkerCommand,
} from '../types';

export const commandClassMap = {
  [CommandType.NoteSequence]: NoteSequence,

  [CommandType.Start]: StartCommand,
  [CommandType.End]: EndCommand,
  [CommandType.Measure]: MeasureCommand,
  [CommandType.BPMChange]: BPMChangeCommand,
  [CommandType.Delay]: DelayCommand,
  [CommandType.Scroll]: ScrollCommand,
  [CommandType.GoGoStart]: GoGoStartCommand,
  [CommandType.GoGoEnd]: GoGoEndCommand,
  [CommandType.BarLineOff]: BarLineOffCommand,
  [CommandType.BarLineOn]: BarLineOnCommand,
  [CommandType.BranchStart]: BranchStartCommand,
  [CommandType.BranchEnd]: BranchEndCommand,
  [CommandType.Section]: SectionCommand,
  [CommandType.Lyric]: LyricCommand,
  [CommandType.LevelHold]: LevelHoldCommand,
  [CommandType.BMScroll]: BMScrollCommand,
  [CommandType.HBScroll]: HBScrollCommand,
  [CommandType.NextSong]: NextSongCommand,
  [CommandType.Direction]: DirectionCommand,
  [CommandType.Sudden]: SuddenCommand,

  'N': BranchMarkerCommand,
  'E': BranchMarkerCommand,
  'M': BranchMarkerCommand,
} as const;
